[theme]

# Primary accent for interactive elements
primaryColor = '#212529'

# Background color for the main content area
backgroundColor = '#212529'

#Background color for secondary elements
secondaryBackgroundColor= '#495057'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif" 